- README.md
- cb_defense_syslog.py
- root/etc/cb/integrations/cb-defense-syslog/cb-defense-syslog.conf.example
Adding customizable http_headers feature.
> Http headers

- PIP_README.md
- README.md
- requirements.txt
- setup.py
- src/cbc_syslog/cb_defense_syslog.py
- Ticket Number: EA-16134
Replaced a built in package that was only compatible with Linux environments. replaced it with a package that was compatible with all platforms.
If this introduces a breaking change, please describe the impact and migration path for existing applications below.
Tests were ran locally in a Windows, Linux and MacOS environment, End to End testing was also completed
> Cbc syslog ea1234

- README.md
- src/cbc_syslog/Dockerfile
Changed Dockerfile to install using pip and removed all RPM build
actions. Updated README with info to use Docker.
Manually tested on Centos7.
- Ticket Number: https://jira.carbonblack.local/browse/CBAPI-1879
- Issue Number: N/A
Updated the Dockerfile to install using pip to align with cross platform changes done previously.  Replaces creating an RPM.
Manual testing on Centos7 machine.
> Updated Dockerfile for pip install

- README.md
- changelog.md
- src/cbc_syslog/config.py
- src/test/fixtures/cef.conf
- src/test/fixtures/json.conf
- src/test/fixtures/leef.conf
- src/test/test_config.py
- src/test/test_syslog.py
N/A
Add more tests and release documentation
Unit tests have been added and ran
> Release note and config test

- README.md
- Ticket Number: N/A
Make it easier to find the "what does this repo's code do?" summary.
> Update README to add implicit heading

- .gitignore
- src/cbc_syslog/util/notifications.py
Email thread
Fix incorrectly indented property assignment
Existing unit tests pass
> Fix incorrectly indented property assignment

- README.md
- src/cbc_syslog/root/etc/cb/integrations/cbc-syslog/cbc-syslog.conf.example
- Ticket Number: N/A
- Issue Number: N/A
From customer issue.
> Update refs to api- URLs with standard dashboard URLs.

- .gitignore
- src/cbc_syslog/util/config.py
- src/cbc_syslog/util/output.py
- src/tests/conftest.py
- src/tests/fixtures/confs/file_out.toml
- src/tests/fixtures/confs/invalid-file.toml
- src/tests/fixtures/tmp/KEEP_EMPTY.md
- src/tests/unit/test_config.py
- src/tests/unit/test_output.py
CBAPI-4464
Add support for outputting to local directory
Unit/functional tests
> Add support for file output

- README.md
CBC-6766
- Ticket Number: N/A
- Issue Number: N/A
Updated README.
Viewed locally.
> Added that syslog connector is not supported in USA GovCloud.

- src/cbc_syslog/core.py
- src/cbc_syslog/util/carbon_black_cloud.py
- src/cbc_syslog/util/config.py
- src/cbc_syslog/util/transform.py
- src/tests/conftest.py
- src/tests/fixtures/confs/alerts-and-audit-logs.toml
- src/tests/fixtures/confs/audit-logs-only.toml
- src/tests/fixtures/mock_audit_logs.py
- src/tests/unit/test_carbon_black_cloud.py
- src/tests/unit/test_config.py
- src/tests/unit/test_core.py
CBAPI-4458
Added support for audit logs
Unit/E2E tests added
> Add Audit logs support

- scripts/cbc_syslog_forwarder.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/core.py
- src/cbc_syslog/util/carbon_black_cloud.py
- src/tests/conftest.py
- src/tests/unit/test_core.py
CBAPI-4469
Add function to check API keys and validate config
Manual and Unit tests
> Add check func

- scripts/cbc_syslog_forwarder.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/core.py
- src/tests/unit/test_core.py
CBAPI-4459
Add history function to enable getting previous alert data as desired
Manual and Unit tests
> History func

- MIGRATION.md
- README.md
- changelog.md
- examples/cef.toml.example
- examples/leef.toml.example
CBAPI-4925
Add migration docs and samples for CEF and LEEF toml files
Markdown preview verification
> Initial migration docs

- README.md
- codeship-steps.yml
- config-test.toml
- docker/amazon/Dockerfile
- docker/rhel/Dockerfile
- docker/suse/Dockerfile
- docker/ubuntu/Dockerfile
- examples/cbc-syslog.cron.example
- examples/cbc-syslog.toml.example
- scripts/cbc_syslog_forwarder
- setup.cfg
- src/cbc_syslog/__init__.py
- src/cbc_syslog/core.py
- src/cbc_syslog/util/example.py
- src/tests/fixtures/confs/wizard-json-file.toml
- src/tests/fixtures/confs/wizard-template-http.toml
- src/tests/fixtures/confs/wizard-template-tcp-tls.toml
- src/tests/fixtures/confs/wizard-template-udp.toml
- src/tests/fixtures/mock_stdin.py
- src/tests/unit/test_core.py
CBAPI-4658
Add a setup wizard to assist in creating a config.toml for the first time
Manual testing as unit tests would be challenging to cover and provide std input
> Add setup wizard command

- README.md
- changelog.md
- examples/cbc-syslog.cron.example
- setup.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/cli.py
- src/tests/unit/test_carbon_black_cloud.py
- src/tests/unit/test_cli.py
- src/tests/unit/test_core.py
CBAPI-4463
Move from using a linux based script to setuptools entrypoints to support more operating systems
Manual testing on Mac and Windows
> Entrypoints

- src/cbc_syslog/util/carbon_black_cloud.py
- src/tests/conftest.py
- src/tests/fixtures/mock_alerts.py
- src/tests/unit/test_carbon_black_cloud.py
- src/tests/unit/test_core.py
N/A
Added code to utilize latest SDK for UAE in 1.5.0
Unit tests
> Add latest sdk code

- .github/pull_request_template.md
- README.md
- changelog.md
- setup.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/core.py
- src/cbc_syslog/util/output.py
- src/tests/unit/test_core.py
#82 
2.0.2 release
**Bug Fixes:**
* Adjust filename output and backup to use base64 instead of datetime
* Fix windows escape issue when using setup or convert commands to create config file
Unit tests and manual test on windows
> Improved Windows support

- requirements.txt
- src/cbc_syslog/core.py
- src/cbc_syslog/util/output.py
DSER-52129
Set UTC timezone for datetime.now
There may be a single large window where the timezone catch up occurs but we should not lose any data on upgrade
Manual and unit tests
> Fix utc for datetime.now

- LICENSE
- changelog.md
- setup.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/cli.py
- src/cbc_syslog/core.py
- src/cbc_syslog/util/carbon_black_cloud.py
- src/cbc_syslog/util/config.py
- src/cbc_syslog/util/example.py
- src/cbc_syslog/util/output.py
- src/cbc_syslog/util/transform.py
- src/tests/conftest.py
- src/tests/unit/test_carbon_black_cloud.py
- src/tests/unit/test_cli.py
- src/tests/unit/test_config.py
- src/tests/unit/test_core.py
- src/tests/unit/test_output.py
- src/tests/unit/test_transform.py
DSER-52129/EA-24395
Release 2.0.3
N/A
> Bug fix release 2.0.3

- LICENSE
- bin/linters.sh
- bin/tests_n_reports.sh
- docker/amazon/Dockerfile
- docker/rhel/Dockerfile
- docker/suse/Dockerfile
- docker/ubuntu/Dockerfile
- requirements.txt
- setup.py
- src/cbc_syslog/__init__.py
- src/cbc_syslog/cli.py
- src/cbc_syslog/core.py
- src/cbc_syslog/util/__init__.py
- src/cbc_syslog/util/carbon_black_cloud.py
- src/cbc_syslog/util/config.py
- src/cbc_syslog/util/example.py
- src/cbc_syslog/util/output.py
- src/cbc_syslog/util/transform.py
- src/tests/conftest.py
- src/tests/fixtures/mock_alerts.py
- src/tests/fixtures/mock_audit_logs.py
- src/tests/fixtures/mock_stdin.py
- src/tests/unit/test_carbon_black_cloud.py
- src/tests/unit/test_cli.py
- src/tests/unit/test_config.py
- src/tests/unit/test_core.py
- src/tests/unit/test_output.py
- src/tests/unit/test_transform.py
https://bsg-jira.broadcom.net/browse/CBAPI-5318
Update copyright dates to 2024 and Broadcom.
Documentation changes only, no code changes.
> CBAPI-5318: Update copyright dates in code
